name: karaoke-app
services:
    frontend:
        build: 
            context: ./frontend        
        ports:
            - "8081:8081"
        volumes:
            - ./frontend:/frontend
            - /frontend/node_modules
        environment:
            - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    backend:
        build: 
            context: ./backend
        ports:
         - "8080:8080"
        volumes:
            - ./backend/src:/backend/src
