name: Backend Ruff

on:
  pull_request:
    paths:
      - '**.py'
    branches: 
      - develop

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
    
      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: backend

      - name: Run Ruff linter
        run: ruff check .
        working-directory: backend

      - name: Run Ruff formatter
        run: ruff format --check .
        working-directory: backend